---
- hosts: all
  sudo: yes
  tasks:
    - name: update a server
      apt: update_cache=yes
    - name: upgrade a server
      apt: upgrade=full
    - name: install git
      apt: pkg=git state=latest
    - name: install vim
      apt: pkg=vim state=latest
    - name: install emacs24
      apt: pkg=emacs24 state=latest
    - name: install nginx
      apt: pkg=nginx state=latest
      notify: 
       - restart nginx
    - name: install mysql
      apt: pkg=mysql-server
    - name: start mysql
      service: name=mysql state=started enabled=yes
    - name: install PHP cli
      apt: name=php5-cli
    - name: install PHP fpm
      apt: name=php5-fpm
    - name: install FuelPHP
      git: repo=https://github.com/fuel/fuel dest=/fuel version=1.7/master recursive=yes
    - name: setup1 FuelPHP
      shell: php /fuel/composer.phar self-update
    - name: setup2 FuelPHP
      shell: php /fuel/composer.phar update
    - name: setup3 FuelPHP
      shell: php /fuel/oil refine install