---
- hosts: all
  sudo: yes
  tasks:
    - name: update a server
      apt: update_cache=yes
    - name: upgrade a server
      apt: upgrade=full

    - name: install git
      apt: pkg=git state=latest

    - name: install vim
      apt: pkg=vim state=latest
    - name: install emacs24
      apt: pkg=emacs24 state=latest

    - name: install nginx
      apt: pkg=nginx state=latest

    - name: install mysql
      apt: pkg=mysql-server state=installed
    - name: install python-mysql
      apt: pkg=python-mysqldb state=installed
    - name: start mysql
      service: name=mysql state=started enabled=yes
    - name: install php5-mysql
      apt: pkg=php5-mysql


    - name: install PHP cli
      apt: name=php5-cli
    - name: install PHP fpm
      apt: name=php5-fpm
    - name: PHPUnit
      get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555

    - name: create db
      mysql_db: db=fuel_dev state=present encoding=utf8
    - name: create db user
      mysql_user: name=root password=root priv=fuel_dev.*:ALL state=present