---
        - name: start mysql
          service: name=mysql state=started enabled=yes

        - name: create db
          mysql_db: db=fuel_dev state=present encoding=utf8
          ignore_errors: yes

        - name: create db user
          mysql_user: name=root password=root priv=fuel_dev.*:ALL state=present
          ignore_errors: yes